### ISSUE TITLE
ReadMe Lacks Content

### ISSUE THREAD

**Issue by ayersdecker** [joes-ta/stuff#1]
**ReadMe** should containt content relavent to the development or distribution of said repository 🔢 🥇

**Comment by joes-ta** [comment]
Hey Decker! How are you doing? I missed the creation notification of this Issue and just got the close notification. Thanks so much for helping out! I created this repo as a demo of Git and GitHub in my CSCS1320 class last week. I'll be sure to use this in class next week (this is break week for us). We did basic init/clone and add/commit/push workflow examples. Issues would be good to see. Perhaps, we could even look at inviting a collaborator ;)

**Comment by ayersdecker** [comment]
Hey, yeah I actually saw the creation of your repository through that beta
GitHub feed. I wasn't overly serious with the issue, was mostly checking
out what it was. I've got free time here and there being a tutor for the
school. Funny enough, I am the only student in my degree program this year
so I have been given "free reign" here. I haven't been back to Corning in
awhile, have I missed anything while I've been gone? Also currently trying
to finish a COVID tracking app before noon today so I'm freaking out! Haha
-Decker A.

**Comment by joes-ta** [comment]
I used your issue for class demonstration yesterday. Thank you, again for helping us out. I pointed out that you have free time and do tutoring 🤣 
When you make it back to Corning, be sure to look us up. There's a new cohort here that hasn't you. And, I did a bit of bragging for you 😆 
Hope that app went well!

**Comment by joes-ta** [comment]
And, I did update the README lol
